---
name: Java CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev
      - master

permissions:
  id-token: write
  contents: write

jobs:
  run-test:
    name: run-test
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        env:
          S3_REPO_USERNAME: ${{ secrets.S3_REPO_USERNAME }}
          S3_REPO_PASSWORD: ${{ secrets.S3_REPO_PASSWORD }}
        run: |
          mvn -U clean test compile deploy --settings .maven-settings/settings.xml \
            -Ds3.username=$S3_REPO_USERNAME -Ds3.password=$S3_REPO_PASSWORD
          mvn package -Dmaven.test.skip=true --settings .maven-settings/settings.xml \
            -Ds3.username=$S3_REPO_USERNAME -Ds3.password=$S3_REPO_PASSWORD
          mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q > mvn-version
          mkdir archive
          cp mvn-version archive
          cp Dockerfile archive
          cp api/target/app.jar archive
          cp -r scripts/* archive

      - name: Archive project artifacts
        uses: actions/upload-artifact@v2
        with:
          name: project-artifacts
          path:
            archive
          retention-days: 1
